### ISSUE TITLE
缺少依赖库

### ISSUE THREAD

**Issue by billhyde** [Netease-Games-AI-Lab-Guangzhou/PerfectDou#1]
感谢您的分享，在运行evaluate.py的时候，好像是缺少perfectdou.env的库，会报   
from perfectdou.env.game import GameEnv
ModuleNotFoundError: No module named 'perfectdou.env'   ​
​我又看了一下源码，perfectdou_agent.py文件中依赖了perfectdou.env.encode
方便的话，麻烦上传一下perfectdou.env，非常感谢~

**Comment by wiljohnhong** [comment]
We are sorry that we might have missed something in the repo, we will fix it soon after the National Day Holiday. Thanks for your interest.

**Comment by billhyde** [comment]
Thank you for your reply, I am looking forward to learning the source code of perfect dou（^^）

**Comment by cookie-yang** [comment]
sorry for the missing, the env module has been added. Please let us know if you have any further problems.

**Comment by billhyde** [comment]
Thank you for your quick reply, I tested it, the project can run, and I am working hard to learn the source code, thank you.
