### ISSUE TITLE
Issue about the demo

### ISSUE THREAD

**Issue by Loydian** [Netease-Games-AI-Lab-Guangzhou/PerfectDou#3]
There may exist some issues in the demo. As usual, landlord is chosen when a player think his cards are good enough to win more ponits. But the demo just assign the characters without considering this, which may result in the landlord has lower WP.

**Comment by wiljohnhong** [comment]
As what we have presented in the paper, the PerfectDou model does not take the bidding phase into consideration, so in the demo we just follow the evaluation setting in paper by randomly assigning the three landlord cards.

**Comment by Ericonaldo** [comment]
Actually this is also the case in most of existing AI systems like DouZero, although DouZero supplements a bidding demo afterwards. We consider to add a demo with bidding stage in the near future.
