### ISSUE TITLE
perfectdou.env.encode not found

### ISSUE THREAD

**Issue by YXalix** [Netease-Games-AI-Lab-Guangzhou/PerfectDou#4]
很感谢你们的分享
when i run  evaluate.py on mac m1，会报 from perfectdou.env.encode import (
ModuleNotFoundError: No module named 'perfectdou.env.encode'

encode.cpython-37m-x86_64-linux-gnu.so文件该如何处理？

**Comment by Ericonaldo** [comment]
如果你用python3.7的话他会自动识别。
如果你用更高版本，把encode.cpython-37m-x86_64-linux-gnu.so改名为encode.so. 但是我们没测试过其他版本的结果准确性.

**Comment by YXalix** [comment]
> 如果你用python3.7的话他会自动识别。 如果你用更高版本，把encode.cpython-37m-x86_64-linux-gnu.so改名为encode.so. 但是我们没测试过其他版本的结果准确性.

我使用的python3.8.5 运行在m1上，修改名字为encode.so，但好像不太行😭，错误提示：
ImportError: dlopen(/Users/nashzhou/Code/PerfectDou/perfectdou/env/encode.so, 0x0002): tried: '/Users/nashzhou/Code/PerfectDou/perfectdou/env/encode.so' (not a mach-o file)

这种方法在colab python3.8.5上是可以的
还是很感谢回复

**Comment by Ericonaldo** [comment]
看起来像是系统的兼容问题

**Comment by dsddasdad** [comment]
我就是用的3.7还是无法识别，文件名改了，也改成3.9了也不行
