### ISSUE TITLE
evaluate过程是不是有问题？

### ISSUE THREAD

**Issue by xiliu** [Netease-Games-AI-Lab-Guangzhou/PerfectDou#6]
evaluate过程中不应该把其他玩家的手牌信息加入到输入状态信息吧，把PerfectDouAgent中的act方法代码改成为如下，测试统计结果和改之前差别很大。
<img width="488" alt="image" src="https://github.com/Netease-Games-AI-Lab-Guangzhou/PerfectDou/assets/7224986/3ee0f1be-fd74-4f74-9cc9-e45989164fee">

**Comment by Ericonaldo** [comment]
https://zhuanlan.zhihu.com/p/570472385
知乎里的第一个评论里回复了一样的问题，你看一下。这个是为了拿到当前对手手里还有几张牌，不会看到对手手牌的

**Comment by xiliu** [comment]
> https://zhuanlan.zhihu.com/p/570472385 知乎里的第一个评论里回复了一样的问题，你看一下。这个是为了拿到当前对手手里还有几张牌，不会看到对手手牌的

嗯，看到了，试过了，没问题的，感谢你的解答
